export const theme = {
  colors: {
    aBg: 'var(--accent-bg)',
    at: 'var(--accent-text)',
    ah: 'var(--accent-hover)',
    bg: 'var(--background)',
    btnBg: 'var(--button-bg)',
    panelBg: 'var(--panel-bg)',
    t: 'var(--text)',
    wt: 'var(--white-text)',
    w: 'var(--white)',
    b: 'var(--black)',
    overlay: 'va  r(--overlay)',
    good: 'var(--good)',
    error: 'var(--error)',
  },
  space: [
    0, 2, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 49, 52, 56, 60, 64, 110,
    128, 256,
  ],
  fonts: {
    montserrat: "'Montserrat', sans-serif",
    marianna: "'Marianna', sans-serif",
  },
  fontSizes: {
    min: '14px',
    normalMin: '16px',
    normal: '20px',
    normalBig: '36px',
    normalMax: '84px',
    max: '96px',
  },
  fontWeights: {
    normal: 400,
    average: 500,
    semiBold: 600,
    bold: 700,
  },
  lineHeights: {
    big: '150%',
    body: '130%',
    normal: '100%',
    heading: 1.25,
  },
  borders: {
    none: 'none',
    normal: '2px solid',
  },
  radii: {
    none: '0',
    inputRadius: '8px',
    normal: '12px',
    round: '50%',
  },
  size: {
    maxVH: '100vh',
    maxVW: '100vw',
    max: '100%',
    half: '50%',
    quarter: '25%',
    socialIcon: '32px',
  },
  shadows: {
    s: 'var(--shadow)',
  },
};
